config/routes.rb
Rails.application.routes.draw do
  resources :tracks do
    patch :reorder, on: :member
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tracks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/track.rb
class Track < ApplicationRecord
  has_rich_text :notes
  has_one_attached :audio

  validate :correct_audio_mime_type

  acts_as_list

  private

  def correct_audio_mime_type
    if audio.attached? && !audio.content_type == 'audio/mpeg'
      errors.add(:audio, 'Must be an MP3 file')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: %i[ show edit update destroy ]
  http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD'], except: :index

  # GET /tracks or /tracks.json
  def index
    @tracks = Track.all.order(position: :asc)
  end

  # GET /tracks/1 or /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks or /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to tracks_url, notice: "Track was successfully created." }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1 or /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to tracks_url, notice: "Track was successfully updated." }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1 or /tracks/1.json
  def destroy
    @track.destroy!

    respond_to do |format|
      format.html { redirect_to tracks_url, notice: "Track was successfully destroyed." }
      format.json { render json: @tracks.map { |track| [track.id, track.title, url_for(track.audio)] if track.audio.attached? } }
    end
  end

  def reorder
    track = Track.find(params[:id])
    track.update!(position: params[:position])

    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:id, :title, :notes, :audio, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
  def humanize(secs)
    [[60, :seconds], [60, :minutes], [24, :hours], [Float::INFINITY, :days]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)

        "#{n.to_i} #{name}" unless n.to_i==0
      end
    }.compact.reverse.join(' ')
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <link rel="shortcut icon" href="./assets/img/favicon.ico" />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="./assets/img/apple-icon.png"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/creativetimofficial/tailwind-starter-kit/compiled-tailwind.min.css"
    />
    <title>The Healing Power of Stömock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="text-gray-800 antialiased">
    <nav
      class="top-0 absolute z-50 w-full flex flex-wrap items-center justify-between px-2 py-3 "
    >
      <div
        class="container px-4 mx-auto flex flex-wrap items-center justify-between"
      >
        <div
          class="w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start"
        >
          <a
            class="text-4xl font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap text-white"
            href="https://simpletunes.fly.dev"
            >The Healing Power of Stömock</a
          >
          <button
            class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
            type="button"
            onclick="toggleNavbar('example-collapse-navbar')"
          >
            <i class="text-white fas fa-bars"></i>
          </button>
        </div>
        <div
          class="lg:flex flex-grow items-center bg-white lg:bg-transparent lg:shadow-none hidden"
          id="example-collapse-navbar"
        >
        </div>
      </div>
    </nav>
    <main class="profile-page">
      <section class="relative block" style="height: 500px;">
        <div
          class="absolute top-0 w-full h-full bg-center bg-cover"
          style='background-image: url(<%= image_url("background.png") %>);'
        >
          <span
            id="blackOverlay"
            class="w-full h-full absolute opacity-50 bg-black"
          ></span>
        </div>
        <div
          class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden"
          style="height: 70px;"
        >
          <svg
            class="absolute bottom-0 overflow-hidden"
            xmlns="http://www.w3.org/2000/svg"
            preserveAspectRatio="none"
            version="1.1"
            viewBox="0 0 2560 100"
            x="0"
            y="0"
          >
            <polygon
              class="text-gray-300 fill-current"
              points="2560 0 2560 100 0 100"
            ></polygon>
          </svg>
        </div>
      </section>
      <section class="relative py-16 bg-gray-300">
        <div class="container mx-auto px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64"
          >
            <div class="px-6">

                <%= yield %>
            </div>
          </div>
        </div>
      </section>
    </main>
    <footer class="relative bg-gray-300 pt-8 pb-6">
      <div
        class="bottom-auto top-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden -mt-20"
        style="height: 80px;"
      >
        <svg
          class="absolute bottom-0 overflow-hidden"
          xmlns="http://www.w3.org/2000/svg"
          preserveAspectRatio="none"
          version="1.1"
          viewBox="0 0 2560 100"
          x="0"
          y="0"
        >
          <polygon
            class="text-gray-300 fill-current"
            points="2560 0 2560 100 0 100"
          ></polygon>
        </svg>
      </div>

        <hr class="my-6 border-gray-400" />
        <div
          class="flex flex-wrap items-center md:justify-between justify-center"
        >
          <div class="w-full md:w-4/12 px-4 mx-auto text-center">
            <div class="text-sm text-gray-600 font-semibold py-1">
              Copyright © 2023 Stomock
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
  <script>
    function toggleNavbar(collapseID) {
      document.getElementById(collapseID).classList.toggle("hidden");
      document.getElementById(collapseID).classList.toggle("block");
    }
  </script>
</html>

app/views/tracks/_form.html.erb
<%= form_with(model: track) do |form| %>
  <% if track.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.rich_text_area :notes %>
  </div>

   <div>
    <%= form.label :audio, style: "display: block" %>
    <%= form.file_field :audio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<tr data-player-target="track" data-audio-url="<%= url_for(track.audio) if track.audio.present? %>" data-title="<%= track.title %>" id="<%= dom_id track %>" data-sortable-target="row" data-id="<%= track.id %>" draggable="true"
  data-action="dragstart->sortable#dragstart dragover->sortable#dragover drop->sortable#drop">
  <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left">
   <i class="fas fa-grip-vertical"></i> <%= track.title %>
  </th>
  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
    <%= humanize(track.audio.metadata[:duration]) if track.audio.present? && track.audio.metadata[:duration] %>
  </td>
  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
    <%= track.notes %>
  </td>
  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
    <%= link_to "<i class='fas fa-edit text-blue-500 mr-1'></i> Edit".html_safe, edit_track_path(track), class: "font-normal text-blue-500" %>
    <%= button_to "<i class='fas fa-trash text-red-500 mr-1'></i> <span class='text-red-500'>Delete</span>".html_safe, track, method: :delete, data: { confirm: 'Are you sure?' }, class: "font-normal text-blue-500" %>
  </td>
</tr>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Show this track", @track %> |
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/index.html.erb
<p style="color: green"><%= notice %></p>

<div data-controller="player">
  <div class="flex flex-wrap justify-center">
    <div
      class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center"
    >
      <div class="relative">
        <div class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16">
        </div>
      </div>
    </div>
    <div class="w-full lg:w-4/12 px-4 lg:order-1">
      <div class="flex justify-center py-4 lg:pt-4 pt-8">
        <div class="mr-4 p-3 text-center">
          <span class="text-xl font-bold block uppercase tracking-wide text-gray-700" id="track-number">
            <%= @tracks.size %>
          </span>
          <span class="text-sm text-gray-500">Tracks</span>
        </div>
        <div class="mr-4 p-3 text-center">
          <div>
            <audio id="audioPlayer" data-player-target="audioPlayer" controls></audio>
            <div id="track-title" data-player-target="trackTitle"></div>
            <button data-action="click->player#previous" data-player-target="prevButton" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-l">Previous</button>
            <button data-action="click->player#next" data-player-target="nextButton" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r">Next</button>          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="flex flex-wrap mt-4 justify-center">
      <div class="w-full xl:w-8/12 mb-12 xl:mb-0 px-4">
        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded">
          <div class="rounded-t mb-0 px-4 py-3 border-0">
            <div class="flex flex-wrap items-center">
              <div class="relative w-full px-4 max-w-full flex-grow flex-1">
                <h3 class="font-semibold text-base text-blueGray-700">
                  Tracks
                </h3>
              </div>
              <div class="relative w-full px-4 max-w-full flex-grow flex-1 text-right">
                <%= link_to "New track", new_track_path, class: "bg-pink-500 active:bg-pink-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1",
                    style: "transition: all 0.15s ease 0s;" %>
              </div>
            </div>
          </div>
          <div class="block w-full overflow-x-auto">
            <!-- Projects table -->
            <table class="items-center w-full border-collapse">
              <thead>
                <tr>
                  <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                    Title
                  </th>
                  <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                    Duration
                  </th>
                  <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                    Notes
                  </th>
                  <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                    Edit
                  </th>
                </tr>
              </thead>
              <tbody data-controller="sortable">
                <% total_duration = 0%>
                <% @tracks.each do |track| %>
                  <% total_duration += track.audio.metadata[:duration] if track.audio.present? && track.audio.metadata[:duration] %>
                  <%= render track %>
                <% end %>
              </tbody>
              <tfoot>
                <tr>
                  <td></td>
                  <td class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                    <%= humanize(total_duration) %>
                  </td>
                  <td colspan="2"></td>
                </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @track %>

<div>
  <%= link_to "Edit this track", edit_track_path(@track) %> |
  <%= link_to "Back to tracks", tracks_path %>

  <%= button_to "Destroy this track", @track, method: :delete %>
</div>